### ISSUE TITLE
Movies not being added to Radarr, Sonarr works fine. 

### ISSUE THREAD

**Issue by Paelsmoessan** [roboticsound/Pulsarr#81]
Radarr Version: 3.1.0.4641
.NET: Yes (5.0.3)

2021-2-22 17:29:17.8|Debug|SabnzbdProxy|Url: http://localhost:8080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
2021-2-22 17:29:18.8|Debug|SabnzbdProxy|Url: http://localhost:8080/api?mode=history&start=0&limit=60&category=movies&apikey=(removed)&output=json
2021-2-22 17:29:19.9|Debug|Api|[GET] /api/v3/queue/details: 200.OK (4 ms)
2021-2-22 17:29:19.9|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2021-2-22 17:29:19.9|Debug|Api|[GET] /api/v3/queue/details: 200.OK (0 ms)
2021-2-22 17:29:19.9|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2021-2-22 17:29:19.9|Debug|Api|[GET] /api/v3/queue/details: 200.OK (0 ms)
2021-2-22 17:29:19.9|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2021-2-22 17:29:19.9|Debug|Api|[GET] /api/v3/queue/details: 200.OK (0 ms)
2021-2-22 17:29:20.0|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2021-2-22 17:29:44.5|Debug|Parser|Parsing string 'imdb: tt0317248'
2021-2-22 17:29:44.5|Debug|Parser|Unable to parse imdb: tt0317248
2021-2-22 17:29:44.6|Debug|Api|[GET] /api/movie/lookup?term=imdb%3A%20tt0317248: 200.OK (87 ms)
2021-2-22 17:29:45.1|Debug|Api|[GET] /api/movie: 200.OK (594 ms)
2021-2-22 17:29:46.0|Debug|Api|[GET] /api/profile: 200.OK (29 ms)
2021-2-22 17:29:46.0|Debug|RootFolderService|Generating list of unmapped folders
2021-2-22 17:29:46.0|Debug|RootFolderService|0 unmapped folders detected.
2021-2-22 17:29:46.0|Debug|RootFolderService|Generating list of unmapped folders
2021-2-22 17:29:46.1|Debug|RootFolderService|0 unmapped folders detected.
2021-2-22 17:29:46.1|Debug|RootFolderService|Generating list of unmapped folders
2021-2-22 17:29:46.1|Debug|RootFolderService|0 unmapped folders detected.
2021-2-22 17:29:46.1|Debug|Api|[GET] /api/rootfolder: 200.OK (144 ms)
2021-2-22 17:29:50.9|Warn|RadarrErrorPipeline|API Error:
BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.qualityProfileId | LineNumber: 0 | BytePositionInLine: 57.

[v3.1.0.4641] Radarr.Http.REST.BadRequestException: BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.qualityProfileId | LineNumber: 0 | BytePositionInLine: 57.
   at Radarr.Http.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 253
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

2021-2-22 17:29:50.9|Debug|Api|[POST] /api/movie: 400.BadRequest (30 ms)

**Comment by TrySpace** [comment]
Working Fork: https://github.com/zebbe152/Pulsarr
