### ISSUE TITLE
[Chrome] "Failed to add movie! Please check it is not already in your collection." Everytime I try to add a movie.

### ISSUE THREAD

**Issue by Stevev91** [roboticsound/Pulsarr#86]
I've tried with different movies that I'm 100% positive do not exist in my collection. I've double-checked everything on settings and even reinstalled the extension to no avail. What can I do? Thank you! 

![pulsarr](https://user-images.githubusercontent.com/88064130/127241640-059d4a49-0717-4ce7-8a90-09d7b34d9cc7.png)

**Comment by DoubtfulTurnip** [comment]
Also having this issue using Firefox. 

This is my log from Radarr; 

```
2021-08-28 12:27:59.6|Warn|RadarrErrorPipeline|API Error:
BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.qualityProfileId | LineNumber: 0 | BytePositionInLine: 54.

[v3.2.2.5080] Radarr.Http.REST.BadRequestException: BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.qualityProfileId | LineNumber: 0 | BytePositionInLine: 54.
   at Radarr.Http.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 253
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

**Comment by TrySpace** [comment]
Try this fork: https://github.com/zebbe152/Pulsarr
